# Generated by Django 4.1.2 on 2022-10-24 19:52

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nutricionista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('N', 'Não Informar')], max_length=1)),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('imc', models.FloatField(verbose_name=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F(models.FloatField()), '/', models.F(models.FloatField())), '*', models.Value(models.FloatField())))),
            ],
        ),
    ]
