# Generated by Django 4.1.2 on 2022-10-24 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutricionista', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutricionista',
            name='imc',
        ),
    ]
